<Project>
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ArcForges.Contracts.Foundation" Version="1.0.0-ci.113.1" />
    <PackageVersion Update="ArcForges.Contracts.Foundation" Version="1.0.0-ci.216.1" Condition="'$(MSBuildProjectName)' == 'LocalRpcAotTests'" />
    <PackageVersion Include="ArcForges.Contracts.LocalRpc.Platform" Version="1.0.0-ci.216.1" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Grpc.AspNetCore.Server" Version="2.83.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.401" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
