<Project>
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <KnownWebAssemblySdkPack Remove="Microsoft.NET.Sdk.WebAssembly.Pack" />
    <KnownWebAssemblySdkPack
      Include="Microsoft.NET.Sdk.WebAssembly.Pack"
      TargetFramework="net10.0"
      WebAssemblySdkPackVersion="10.0.11" />
  </ItemGroup>
  <Import Project="eng\build\NoInlineVersions.targets" />
</Project>
