# SPDX-License-Identifier: AGPL-3.0-only
"""Emit the Contributions test catalog from its single JSON fixture input."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any


KINDS = {
    "Capability",
    "Action",
    "ContextProvider",
    "ArtifactHandler",
    "SuggestedTask",
    "DeepLink",
    "LifecycleHandler",
}
KEY_PATTERN = re.compile(r"[a-z0-9]+(?:[.-][a-z0-9]+)*\Z")
IDENTIFIER_PATTERN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


def fail(message: str) -> None:
    raise ValueError(message)


def quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def validate_document(document: Any) -> list[dict[str, Any]]:
    if not isinstance(document, dict) or set(document) != {"catalogs"}:
        fail("input must contain exactly one 'catalogs' array")
    catalogs = document["catalogs"]
    if not isinstance(catalogs, list) or not catalogs:
        fail("'catalogs' must be a non-empty array")

    seen_owners: set[str] = set()
    normalized: list[dict[str, Any]] = []
    for catalog in catalogs:
        if not isinstance(catalog, dict) or set(catalog) != {"className", "ownerProductId", "contributions"}:
            fail("each catalog must contain exactly className, ownerProductId, and contributions")
        name = catalog["className"]
        owner = catalog["ownerProductId"]
        contributions = catalog["contributions"]
        if not isinstance(name, str) or not IDENTIFIER_PATTERN.fullmatch(name):
            fail("catalog className must be a C# identifier")
        if not isinstance(owner, str) or not KEY_PATTERN.fullmatch(owner):
            fail("ownerProductId must be a canonical lower-case key")
        if owner in seen_owners:
            fail(f"duplicate ownerProductId: {owner}")
        seen_owners.add(owner)
        if not isinstance(contributions, list):
            fail(f"contributions for {owner} must be an array")

        seen_ids: set[str] = set()
        entries: list[dict[str, Any]] = []
        for entry in contributions:
            if not isinstance(entry, dict) or set(entry) != {"id", "kind", "toolSchemaId"}:
                fail("each contribution must contain exactly id, kind, and toolSchemaId")
            contribution_id = entry["id"]
            kind = entry["kind"]
            schema = entry["toolSchemaId"]
            if not isinstance(contribution_id, str) or not KEY_PATTERN.fullmatch(contribution_id):
                fail("contribution id must be a canonical lower-case key")
            if not contribution_id.startswith(owner + "."):
                fail(f"contribution {contribution_id} is outside owner namespace {owner}")
            if contribution_id in seen_ids:
                fail(f"duplicate contribution id: {contribution_id}")
            seen_ids.add(contribution_id)
            if not isinstance(kind, str) or kind not in KINDS:
                fail(f"unknown contribution kind for {contribution_id}: {kind!r}")
            if schema is not None:
                if not isinstance(schema, str) or not KEY_PATTERN.fullmatch(schema):
                    fail(f"toolSchemaId for {contribution_id} must be null or a canonical key")
                if kind != "Capability":
                    fail(f"toolSchemaId is only valid for a Capability: {contribution_id}")
            entries.append({"id": contribution_id, "kind": kind, "toolSchemaId": schema})

        normalized.append({"className": name, "ownerProductId": owner, "contributions": sorted(entries, key=lambda item: item["id"])})

    names = [catalog["className"] for catalog in normalized]
    if len(names) != len(set(names)):
        fail("catalog className values must be unique")
    return sorted(normalized, key=lambda item: item["ownerProductId"])


def emit(catalogs: list[dict[str, Any]]) -> str:
    lines = [
        "// <auto-generated />",
        "// SPDX-License-Identifier: AGPL-3.0-only",
        "#nullable enable",
        "using ArcForges.Contributions;",
        "",
        "namespace ArcForges.Contributions.Tests.Generated;",
        "",
    ]
    for catalog in catalogs:
        lines.extend(
            [
                f"internal sealed class {catalog['className']} : IContributionCatalog",
                "{",
                "    private static readonly IReadOnlyList<ContributionDefinition> descriptorSnapshot =",
                "        Array.AsReadOnly<ContributionDefinition>(",
                "            [",
            ]
        )
        for entry in catalog["contributions"]:
            schema = "null" if entry["toolSchemaId"] is None else quote(entry["toolSchemaId"])
            lines.append(
                "                new ContributionDefinition("
                f"{quote(entry['id'])}, {quote(catalog['ownerProductId'])}, "
                f"ContributionKind.{entry['kind']}, {schema}),"
            )
        lines.extend(
            [
                "        ]);",
                "",
                f"    public string OwnerProductId {{ get; }} = {quote(catalog['ownerProductId'])};",
                "    public IReadOnlyList<ContributionDefinition> Descriptors => descriptorSnapshot;",
                "    public string Fingerprint => ContributionCatalogFingerprint.Compute(OwnerProductId, descriptorSnapshot);",
                "}",
                "",
            ]
        )
    lines.extend(
        [
            "internal static class GeneratedContributionCatalogs",
            "{",
            "    internal static IReadOnlyList<IContributionCatalog> All { get; } =",
            "        Array.AsReadOnly<IContributionCatalog>(",
            "            [",
        ]
    )
    for catalog in catalogs:
        lines.append(f"                new {catalog['className']}(),")
    lines.extend(
        [
            "            ]);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def matches_source(input_path: Path, output_path: Path) -> bool:
    document = json.loads(input_path.read_text(encoding="utf-8"))
    expected = emit(validate_document(document))
    return output_path.is_file() and output_path.read_text(encoding="utf-8") == expected


def verify_drift_rejection(input_path: Path) -> None:
    original = json.loads(input_path.read_text(encoding="utf-8"))
    mutated = json.loads(json.dumps(original))
    changed = False
    for catalog in mutated["catalogs"]:
        for contribution in catalog["contributions"]:
            if contribution["kind"] == "Capability" and contribution["toolSchemaId"] is not None:
                contribution["toolSchemaId"] += ".changed"
                changed = True
                break
        if changed:
            break
    if not changed:
        fail("drift regression requires a schema-bearing capability fixture")

    with tempfile.TemporaryDirectory(prefix="arcforges-contribution-catalog-") as temporary:
        root = Path(temporary)
        temporary_input = root / "contributions.json"
        temporary_output = root / "ContributionCatalog.g.cs"
        temporary_input.write_text(json.dumps(original, indent=2) + "\n", encoding="utf-8")
        temporary_output.write_text(emit(validate_document(original)), encoding="utf-8", newline="\n")
        if not matches_source(temporary_input, temporary_output):
            fail("drift regression could not recognize a freshly emitted catalog")

        temporary_input.write_text(json.dumps(mutated, indent=2) + "\n", encoding="utf-8")
        if matches_source(temporary_input, temporary_output):
            fail("check mode accepted changed catalog input with stale generated output")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-drift", action="store_true")
    args = parser.parse_args()

    try:
        if args.verify_drift:
            verify_drift_rejection(args.input)
            return 0
        if args.output is None:
            parser.error("--output is required unless --verify-drift is selected")
        document = json.loads(args.input.read_text(encoding="utf-8"))
        expected = emit(validate_document(document))
        if args.check:
            if not matches_source(args.input, args.output):
                print(f"generated catalog is stale: {args.output}", file=sys.stderr)
                return 1
            return 0
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(expected, encoding="utf-8", newline="\n")
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as exception:
        print(f"catalog generation failed: {exception}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
