<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <Import Project="../../eng/build/desktop-aot.props" />
  <Import Project="../../eng/build/desktop-rids.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <LicenceBoundary>AGPL</LicenceBoundary>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ArcForges.Contracts.LocalRpc.Platform" />
    <PackageReference Include="Grpc.AspNetCore.Server" />
    <PackageReference Include="Grpc.Net.Client" />
  </ItemGroup>
</Project>
