// SPDX-License-Identifier: AGPL-3.0-only

using System.Security.Cryptography;
using System.Text.Json;
using ArcForges.Build.Policy.Architecture;

namespace ArcForges.Tests.ArchitectureTests;

/// <summary>
/// Regressions for the shared engine's generated-type recognition, driven through the real AT-11 and AT-12 rules: a
/// class-level generator stamp or a leading <c>&lt;auto-generated</c> header comment is recognised, nothing else is,
/// and recognition never replaces the schema binding that AT-12 also requires.
/// </summary>
public sealed class GeneratedTypeRecognitionTests
{
    private const string Schema = "syntax = \"proto3\"; message WireMessage { int32 value = 1; }";
    private const string Wire = "namespace Wire; public sealed class WireMessage { public int Value { get; set; } }";

    [Xunit.Theory]
    [Xunit.InlineData("// <auto-generated/>\n" + Wire)]
    [Xunit.InlineData("// <auto-generated>\n//   Generated by the protocol buffer compiler.\n// </auto-generated>\n#nullable disable\n" + Wire)]
    [Xunit.InlineData("/* <auto-generated> */\n" + Wire)]
    [Xunit.InlineData("namespace Wire; [System.CodeDom.Compiler.GeneratedCode(\"protoc\", \"1\")] public sealed class WireMessage { }")]
    [Xunit.InlineData("namespace Wire; [System.CodeDom.Compiler.GeneratedCode(\"ArcForges.SchemaGenerator\", \"1\")] public sealed class WireMessage { }")]
    public void AWireTypeFromAGeneratorStampOrALeadingHeaderSatisfiesAt12(string source)
    {
        ArgumentNullException.ThrowIfNull(source);
        using var fixture = Fixture.Contracts(("WireMessage.cs", source));
        Xunit.Assert.Empty(fixture.Check("AT-12"));
    }

    [Xunit.Theory]
    [Xunit.InlineData(Wire)]
    [Xunit.InlineData("// authored by hand\n" + Wire)]
    [Xunit.InlineData("using System;\n// <auto-generated/>\n" + Wire)]
    [Xunit.InlineData("namespace Wire; // <auto-generated/>\npublic sealed class WireMessage { public int Value { get; set; } }")]
    [Xunit.InlineData("namespace Wire; public sealed class WireMessage { public string Note = \"// <auto-generated\"; }")]
    [Xunit.InlineData("namespace Wire;\npublic sealed class WireMessage\n{\n    // <auto-generated/>\n    public int Value { get; set; }\n}")]
    [Xunit.InlineData("/// <auto-generated/>\n" + Wire)]
    [Xunit.InlineData("namespace Wire; [System.CodeDom.Compiler.GeneratedCode(\"someone-else\", \"1\")] public sealed class WireMessage { }")]
    public void AnAuthoredOrNonLeadingMarkerWireTypeStillFailsAt12(string source)
    {
        ArgumentNullException.ThrowIfNull(source);
        using var fixture = Fixture.Contracts(("WireMessage.cs", source));
        Xunit.Assert.Contains(fixture.Check("AT-12"), finding => finding.Message.Contains("Wire.WireMessage", StringComparison.Ordinal));
    }

    [Xunit.Fact]
    public void ARecognisedTypeWithoutASchemaBindingOrWithAWrongHashStillFailsAt12()
    {
        string header = "// <auto-generated/>\n" + Wire;
        using (var unbound = Fixture.Contracts(Binding.None, ["Wire.WireMessage"], ("WireMessage.cs", header)))
        {
            Xunit.Assert.Single(unbound.Check("AT-12"));
        }

        using (var wrongHash = Fixture.Contracts(Binding.WrongHash, ["Wire.WireMessage"], ("WireMessage.cs", header)))
        {
            Xunit.Assert.Single(wrongHash.Check("AT-12"));
        }

        using var bound = Fixture.Contracts(("WireMessage.cs", header));
        Xunit.Assert.Empty(bound.Check("AT-12"));
    }

    [Xunit.Fact]
    public void NestedTypesFollowTheirContainerAndPartialTypesMustBeGeneratedInEveryDeclaration()
    {
        const string container = "namespace Wire; public sealed class Outer { public sealed class WireMessage { public int Value { get; set; } } }";
        using (var generated = Fixture.Contracts(Binding.Correct, ["Wire.Outer", "Wire.Outer.WireMessage"], ("Outer.cs", "// <auto-generated/>\n" + container)))
        {
            Xunit.Assert.Empty(generated.Check("AT-12"));
        }

        using (var authored = Fixture.Contracts(Binding.Correct, ["Wire.Outer", "Wire.Outer.WireMessage"], ("Outer.cs", container)))
        {
            Xunit.Assert.Equal(2, authored.Check("AT-12").Length);
        }

        const string part = "namespace Wire; public sealed partial class WireMessage { }";
        using (var mixed = Fixture.Contracts(("Generated.cs", "// <auto-generated/>\n" + part), ("Authored.cs", part)))
        {
            Xunit.Assert.Single(mixed.Check("AT-12"));
        }

        using var allGenerated = Fixture.Contracts(("Generated.cs", "// <auto-generated/>\n" + part), ("More.cs", "// <auto-generated/>\n" + part));
        Xunit.Assert.Empty(allGenerated.Check("AT-12"));
    }

    [Xunit.Theory]
    [Xunit.InlineData("// <auto-generated/>\n", true)]
    [Xunit.InlineData("", false)]
    [Xunit.InlineData("using System;\n// <auto-generated/>\n", false)]
    public void TheGeneratedInterfaceOfALocalServiceIsRecognisedByTheSameRuleAt11(string header, bool accepted)
    {
        ArgumentNullException.ThrowIfNull(header);
        using var fixture = Fixture.LocalService(
            ("GeneratedRpc.cs", header + "public static class GeneratedRpc { public abstract class ServiceBase { public abstract int Call(int value); } }"),
            ("Service.cs", "internal interface IPort { int Call(); } internal sealed class Port : IPort { int IPort.Call() => 1; }\n"
                + "public sealed class Service : GeneratedRpc.ServiceBase { private readonly IPort _port = new Port(); public override int Call(int value) => 1; }"));
        Xunit.Assert.Equal(accepted, fixture.Check("AT-11").Length == 0);
    }

    private enum Binding
    {
        Correct,
        None,
        WrongHash,
    }

    private sealed class Fixture : IDisposable
    {
        private const string SourceCommit = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        private readonly string _root = Path.Combine(Path.GetTempPath(), "arcforges-recognition-" + Guid.NewGuid().ToString("N"));
        private readonly ProjectFacts _project;
        private readonly Microsoft.CodeAnalysis.CSharp.CSharpCompilation _compilation;
        private readonly List<WireTypeBinding> _wireTypes = [];
        private readonly List<LocalServiceBinding> _services = [];
        private readonly Dictionary<string, string> _toolchains = new(StringComparer.Ordinal);

        private Fixture(ProjectRole role, (string Name, string Source)[] files)
        {
            _ = Directory.CreateDirectory(Path.Combine(_root, "subject"));
            File.WriteAllText(Path.Combine(_root, "subject", "subject.csproj"), "<Project />");
            File.WriteAllText(Path.Combine(_root, "subject", "packages.lock.json"),
                JsonSerializer.Serialize(new { version = 1, dependencies = new Dictionary<string, object> { ["net10.0"] = new { } } }));
            File.WriteAllText(Path.Combine(_root, "global.json"), "{\"sdk\":{\"version\":\"10.0.400\"}}");
            _toolchains["global.json"] = Hash(Path.Combine(_root, "global.json"));
            _project = new ProjectFacts(new ProjectClassification("subject/subject.csproj", role, "DesktopPlatform"), "net10.0", "Library",
                "AGPL-3.0-only", "AGPL", [], files.Select(file => file.Name).ToArray(), [], new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["ManagePackageVersionsCentrally"] = "true",
                    ["RestorePackagesWithLockFile"] = "true",
                    ["EnableTrimAnalyzer"] = "true",
                    ["EnableAotAnalyzer"] = "true",
                }, new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase));
            _compilation = FixtureCompiler.Compile("subject", files.ToDictionary(file => file.Name, file => file.Source, StringComparer.Ordinal), []);
        }

        public static Fixture Contracts(params (string Name, string Source)[] files) => Contracts(Binding.Correct, ["Wire.WireMessage"], files);

        public static Fixture LocalService(params (string Name, string Source)[] files)
        {
            var fixture = new Fixture(ProjectRole.LocalRpcAdapter, files);
            fixture._services.Add(new("Service", "GeneratedRpc.ServiceBase", "IPort"));
            return fixture;
        }

        public PolicyFinding[] Check(string rule) => PolicyEngine.Check(
            new RepositoryFacts(_root, "DesktopPlatform", [_project], [], []),
            new RepositoryPolicyConfiguration(SourceCommit, _toolchains, new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase),
                new HashSet<string>(StringComparer.Ordinal), _services, _wireTypes, []),
            new Dictionary<string, Microsoft.CodeAnalysis.CSharp.CSharpCompilation>(StringComparer.Ordinal) { [_project.Classification.Path] = _compilation },
            new DateOnly(2026, 10, 4)).Where(finding => finding.Rule == rule).ToArray();

        public void Dispose() => Directory.Delete(_root, recursive: true);

        public static Fixture Contracts(Binding bind, string[] typeNames, params (string Name, string Source)[] files)
        {
            var fixture = new Fixture(ProjectRole.Contracts, files);
            string schema = Path.Combine(fixture._root, "message.proto");
            File.WriteAllText(schema, Schema);
            if (bind != Binding.None)
            {
                string hash = bind == Binding.WrongHash ? new string('0', 64) : Hash(schema);
                fixture._wireTypes.AddRange(typeNames.Select(name => new WireTypeBinding(name, "message.proto", hash)));
            }

            return fixture;
        }

        private static string Hash(string path) => Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(path)));
    }
}
