# SPDX-License-Identifier: AGPL-3.0-only
"""Self-contained delivery validation/rendering adapted from Plan tools/delivery.py.
Source identity recorded by provenance. No adjacent source or Design code executes.
"""
from __future__ import annotations
from collections import Counter, defaultdict, deque
from pathlib import Path
import heapq
import json
import re
import tempfile
import design_corpus as corpus

PREFERRED_HOMES = [
    'docs/decisions/phase-2-specification-decisions.md',
    'docs/decisions/phase-1-foundation-decisions.md',
    'docs/assurance/open-gates-register.md',
    'docs/assurance/release-gates.md',
    'docs/requirements/01-normative-glossary-and-invariants.md',
    'docs/planning/implementation-sequence.md',
    'docs/planning/delivery/README.md',
]

class Fail(ValueError):
    pass

PLAN_ROOT = Path(__file__).resolve().parents[1]

GRAPH_REL = 'docs/planning/delivery/delivery-graph.json'

DELIVERY_REL = 'docs/planning/delivery'

WP_REL = 'docs/planning/work-packages'

TASK_ID = re.compile(r'^[A-Z]{2,6}\.\d{2}$')

SLICE_ID = re.compile(r'^ADOPT\.\d{2}\.[a-z][a-z0-9-]*$')

ROOT_ADOPTION = 'ADOPT.01'

SUB_ID = re.compile(r'^SUB-[a-z0-9]+(?:-[a-z0-9]+)*$')

RES_ID = re.compile(r'^RES-[a-z0-9]+(?:-[a-z0-9]+)*$')

POB_ID = re.compile(r'^WP-(\d{2}):[a-z0-9]+(?:-[a-z0-9]+)*$')

SUBSTEP = re.compile(r'^WP-(\d{2})\.(\d{2})$')

DECISION = re.compile(r'^P2-\d{3}$')

START_TYPES = {'contract', 'artifact', 'design', 'release'}

COMPLETE_TYPES = {'integration'}

KINDS = {'governance', 'contract', 'producer', 'feature', 'service', 'proof', 'integration',
         'acceptance', 'release', 'adoption'}

SIZES = {'S': 1, 'M': 2, 'L': 4, 'XL': 8}

BASELINE = {'accepted', 'not-started'}

SUB_CLASSES = {'value', 'behavior'}

MODES = {'append', 'exclusive', 'read', 'regenerate'}

CORPUS_ID = re.compile(r'(?<![\w-])(?:WP-\d{2}(?:\.\d{2})?|P2-\d{3}|F-[A-Z]{2}-[1-9]\d*|'
                       r'[A-Z][A-Z0-9]{0,5}-(?:[A-Z]\d{1,3}|\d{2,3}[a-z]?))(?![\w-]|\.\d)')

LINK = re.compile(r'\[([^\]\n]+)\]\(([^)\n]+)\)')

ANCHOR = re.compile(r'<a\s+id="([^"]+)"\s*>\s*</a>')

BEGIN = '<!-- delivery-graph:begin (generated by Plan tools/delivery.py; do not edit) -->'

END = '<!-- delivery-graph:end -->'

def slug(task_id: str) -> str:
    return 'task-' + task_id.lower().replace('.', '-')

def key_of(item_id: str) -> str:
    """Ref, branch and ledger file key of an ID: lower case, dots replaced by hyphens.

    Git for Windows rejects refs and paths whose stem is a reserved device name (CON, PRN, AUX,
    NUL, COM1-9, LPT1-9) followed by an extension, so `con.02` can be neither a claim branch, a
    task branch nor a ledger file on the Windows workstations. Upper case is avoided because
    `CON-02` would read as a corpus identifier in generated Design views."""
    return item_id.lower().replace('.', '-')

def role_id(repo: str) -> str:
    return f'integration:{repo}'

def load_json(path: Path):
    def hook(pairs):
        out = {}
        for k, v in pairs:
            if k in out:
                raise Fail(f'duplicate JSON key {k} in {path}')
            out[k] = v
        return out
    return json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=hook)

def wp_files(design: Path) -> dict[str, Path]:
    files = {}
    for p in sorted((design / WP_REL).glob('[0-9][0-9]-*.md')):
        files[p.name[:2]] = p
    return files

def substeps(design: Path) -> dict[str, dict]:
    """Every active numbered substep, parsed from the obligation catalogue headings."""
    out = {}
    for wp, p in wp_files(design).items():
        for line in p.read_text(encoding='utf-8').splitlines():
            m = re.match(r'^### WP-(\d{2})\.(\d{2}) — (.+?)\s*$', line)
            if m:
                sid = f'WP-{m[1]}.{m[2]}'
                out[sid] = {'id': sid, 'wp': m[1], 'title': m[3].rstrip('.'), 'file': p.name}
    return out

def anchor_homes(design: Path) -> dict[str, list[str]]:
    """Map rule identifiers to the documents that define `rule-<id>` anchors."""
    homes = defaultdict(list)
    for p in sorted((design / 'docs').rglob('*.md')):
        rel = p.relative_to(design).as_posix()
        if rel.startswith('docs/deprecated-inputs/') and not rel.endswith('README.md'):
            continue
        for a in ANCHOR.findall(p.read_text(encoding='utf-8')):
            if a.startswith('rule-'):
                homes[a[5:]].append(rel)
    return homes

class Linker:
    def __init__(self, design: Path, from_rel: str):
        self.design = design
        self.from_dir = str(Path(from_rel).parent.as_posix())
        self.homes = anchor_homes(design)
        self.unknown: set[str] = set()

    def rel(self, target_rel: str) -> str:
        import posixpath
        return posixpath.relpath(target_rel, self.from_dir)

    def home(self, ident: str) -> str | None:
        key = ident.lower()
        m = SUBSTEP.match(ident) or re.match(r'^WP-(\d{2})$', ident)
        if m:
            files = wp_files(self.design)
            f = files.get(m[1])
            return f'{WP_REL}/{f.name}' if f else None
        cands = self.homes.get(key, [])
        if not cands:
            return None
        if len(cands) == 1:
            return cands[0]
        for pref in PREFERRED_HOMES:
            if pref in cands:
                return pref
        return cands[0]

    def link(self, ident: str) -> str:
        h = self.home(ident)
        if not h:
            self.unknown.add(ident)
            return ident
        return f'[{ident}]({self.rel(h)}#rule-{ident.lower()})'

    def text(self, s: str) -> str:
        """Link every corpus identifier outside existing links; strip code spans around IDs."""
        if not s:
            return ''
        s = s.replace('\r', ' ').replace('\n', ' ').replace('|', '/')
        s = re.sub(r'`([^`]*)`', lambda m: m[1] if CORPUS_ID.search(m[1]) else m[0], s)
        out, pos = [], 0
        spans = [m.span() for m in LINK.finditer(s)]
        for m in CORPUS_ID.finditer(s):
            if any(a <= m.start() < b for a, b in spans):
                continue
            out.append(s[pos:m.start()])
            out.append(self.link(m[0]))
            pos = m.end()
        out.append(s[pos:])
        return ''.join(out)

class Graph:
    def __init__(self, design: Path):
        self.design = design
        self.data = load_json(design / GRAPH_REL)
        self.tasks = {t['id']: t for t in self.data['tasks']}
        self.lanes = {l['id']: l for l in self.data['lanes']}
        self.repos = {r['id']: r for r in self.data['repositories']}
        self.subs = {s['id']: s for s in self.data.get('substitutes', [])}
        self.res = {r['id']: r for r in self.data.get('sharedResources', [])}
        self.pobs = {p['id']: p for p in self.data.get('packageObligations', [])}
        self.gates = {g['gate']: g for g in self.data.get('gates', [])}
        self.catalogue = substeps(design)
        # Adoption slices (DLV-22): one independently claimable unit per repository and lane. They are
        # scheduling nodes like tasks; the repository adoption task completes after all of its slices.
        self.slices = {s['id']: s for s in self.data.get('adoptionSlices', [])}
        self.slice_of = {(s['repo'], s['lane']): s['id'] for s in self.slices.values()}
        for s in self.slices.values():
            self.tasks[s['id']] = {
                'id': s['id'], 'title': s['title'], 'lane': 'adoption', 'repo': s['repo'], 'kind': 'adoption',
                'size': 'S', 'slice': True, 'lanesOpened': s['lane'], 'baseline': {'state': 'not-started'},
                'obligations': [{'ref': 'P2-018', 'part': f'adoption slice for {s["repo"]} lane {s["lane"]}'}],
                'start': [{'type': 'artifact', 'task': ROOT_ADOPTION, 'need': 'frozen baseline record',
                           'why': 'every slice classifies against the same frozen heads and receipts'}],
                'complete': []}
            parent = self.tasks.get(s['adoptionTask'])
            if parent is not None and not any(e['task'] == s['id'] for e in parent['complete']):
                parent['complete'].append({'type': 'integration', 'task': s['id'], 'need': 'slice recorded',
                                           'why': 'the repository adoption record closes after every slice of the repository'})

    def slice_tasks(self, sid):
        s = self.slices[sid]
        return sorted(tid for tid, t in self.tasks.items()
                      if not t.get('slice') and t['repo'] == s['repo'] and t['lane'] == s['lane'])

    def start_edges(self, t):
        return [e for e in t.get('start', [])]

    def complete_edges(self, t):
        return [e for e in t.get('complete', [])]

    def entry(self, tid):
        """Adoption entry of a task (DLV-22): the slice of its repository and lane, if any."""
        t = self.tasks[tid]
        if t.get('kind') == 'adoption' or t['baseline']['state'] == 'accepted':
            return None
        sid = self.slice_of.get((t['repo'], t['lane']))
        if sid:
            return sid
        a = self.repos.get(t['repo'], {}).get('adoptionTask')
        return None if not a or a == tid else a

    def starts(self, tid):
        t = self.tasks[tid]
        s = [e['task'] for e in t.get('start', [])]
        a = self.entry(tid)
        return s + ([a] if a and a not in s else [])

    def preds(self, tid):
        t = self.tasks[tid]
        return self.starts(tid) + [e['task'] for e in t.get('complete', [])]

    def succ_map(self):
        succ = defaultdict(set)
        for tid, t in self.tasks.items():
            for e in t.get('start', []) + t.get('complete', []):
                succ[e['task']].add(tid)
        return succ

    def events(self):
        """Event graph (DLV-21): D(t)=delivered, C(t)=complete.

        D(t) needs D(s) for each contract/artifact/design start prerequisite s (and the adoption entry),
        C(s) for each release prerequisite; C(t) needs D(t) and C(s) for each completion prerequisite s.
        """
        adj = defaultdict(set)
        for tid, t in self.tasks.items():
            for e in t.get('start', []):
                adj[('D', tid)].add(('C' if e['type'] == 'release' else 'D', e['task']))
            ent = self.entry(tid)
            if ent:
                adj[('D', tid)].add(('C', ent))
            adj[('C', tid)].add(('D', tid))
            for e in t.get('complete', []):
                adj[('C', tid)].add(('C', e['task']))
        return adj

    def event_order(self):
        adj = self.events()
        nodes = {(k, t) for t in self.tasks for k in ('D', 'C')}
        indeg = {n: 0 for n in nodes}
        rev = defaultdict(set)
        for n, ps in adj.items():
            for p in ps:
                if p in nodes:
                    indeg[n] += 1
                    rev[p].add(n)
        q = deque(sorted(n for n, d in indeg.items() if d == 0))
        order = []
        while q:
            n = q.popleft()
            order.append(n)
            for m in sorted(rev.get(n, ())):
                indeg[m] -= 1
                if indeg[m] == 0:
                    q.append(m)
        stuck = sorted({t for (k, t), d in indeg.items() if d > 0})
        return order, stuck

    def topo(self):
        indeg = {t: 0 for t in self.tasks}
        succ = self.succ_map()
        for tid in self.tasks:
            for p in set(self.preds(tid)):
                if p in self.tasks:
                    indeg[tid] += 1
        q = deque(sorted(t for t, d in indeg.items() if d == 0))
        order = []
        while q:
            n = q.popleft()
            order.append(n)
            for s in sorted(succ.get(n, ())):
                indeg[s] -= 1
                if indeg[s] == 0:
                    q.append(s)
        return order, [t for t, d in indeg.items() if d > 0]

    def ancestors(self, tid, cache={}):
        key = (id(self), tid)
        if key in cache:
            return cache[key]
        seen, stack = set(), list(self.preds(tid))
        while stack:
            p = stack.pop()
            if p in seen or p not in self.tasks:
                continue
            seen.add(p)
            stack.extend(self.preds(p))
        cache[key] = seen
        return seen

    def obligation_map(self):
        m = defaultdict(list)
        for t in self.data['tasks']:
            for o in t.get('obligations', []):
                m[o['ref']].append((t['id'], o.get('part', '')))
        return m

def validate(g: Graph) -> tuple[list[str], list[str]]:
    errors, warnings = [], []
    ids = [t['id'] for t in g.data['tasks']]
    for tid, n in Counter(ids).items():
        if n > 1:
            errors.append(f'duplicate task id {tid}')
    required = ['id', 'title', 'lane', 'repo', 'kind', 'size', 'obligations', 'outcome', 'start',
                'complete', 'writes', 'validation', 'evidence', 'baseline']
    for t in g.data['tasks']:
        tid = t.get('id', '?')
        for f in required:
            if f not in t:
                errors.append(f'{tid}: missing field {f}')
        if not TASK_ID.match(tid):
            errors.append(f'{tid}: invalid task id format')
        if CORPUS_ID.search(t.get('title', '')):
            errors.append(f'{tid}: title contains a corpus identifier; keep identifiers in obligations')
        if t.get('lane') not in g.lanes:
            errors.append(f'{tid}: unknown lane {t.get("lane")}')
        elif not tid.startswith(g.lanes[t['lane']]['prefix'] + '.'):
            errors.append(f'{tid}: prefix does not match lane {t["lane"]}')
        if t.get('repo') not in g.repos:
            errors.append(f'{tid}: unknown repository {t.get("repo")}')
        for r in t.get('alsoTouches', []):
            if r not in g.repos:
                errors.append(f'{tid}: unknown touched repository {r}')
        if t.get('kind') not in KINDS:
            errors.append(f'{tid}: unknown kind {t.get("kind")}')
        if t.get('size') not in SIZES:
            errors.append(f'{tid}: unknown size {t.get("size")}')
        if not t.get('obligations'):
            errors.append(f'{tid}: no obligations')
        for o in t.get('obligations', []):
            ref = o.get('ref', '')
            if SUBSTEP.match(ref):
                if ref not in g.catalogue:
                    errors.append(f'{tid}: obligation {ref} is not an active substep')
            elif POB_ID.match(ref):
                if ref not in g.pobs:
                    errors.append(f'{tid}: unknown package obligation {ref}')
            elif DECISION.match(ref):
                if t.get('kind') not in {'adoption', 'governance'}:
                    errors.append(f'{tid}: decision obligation {ref} is reserved for adoption/governance tasks')
            else:
                errors.append(f'{tid}: invalid obligation reference {ref}')
            if not o.get('part'):
                errors.append(f'{tid}: obligation {ref} lacks part text')
        for kind, allowed in (('start', START_TYPES), ('complete', COMPLETE_TYPES)):
            seen = set()
            for e in t.get(kind, []):
                tgt = e.get('task')
                if e.get('type') not in allowed:
                    errors.append(f'{tid}: {kind} edge to {tgt} has invalid type {e.get("type")}')
                if tgt not in g.tasks:
                    errors.append(f'{tid}: {kind} edge to unknown task {tgt}')
                if tgt == tid:
                    errors.append(f'{tid}: self edge')
                if tgt in seen:
                    errors.append(f'{tid}: duplicate {kind} edge to {tgt}')
                seen.add(tgt)
                if not (e.get('why') or '').strip() or not (e.get('need') or '').strip():
                    errors.append(f'{tid}: {kind} edge to {tgt} lacks need/why')
                if e.get('type') == 'release' and t.get('kind') not in {'release', 'acceptance'}:
                    errors.append(f'{tid}: release edge on a non-release task')
        for s in t.get('substitutes', []):
            if s not in g.subs:
                errors.append(f'{tid}: unknown substitute {s}')
        for sh in t.get('shared', []):
            if sh.get('resource') not in g.res:
                errors.append(f'{tid}: unknown shared resource {sh.get("resource")}')
            if sh.get('mode') not in MODES:
                errors.append(f'{tid}: invalid shared mode {sh.get("mode")}')
        for w in t.get('writes', []):
            repo = w.split(':', 1)[0]
            if ':' not in w or (repo not in g.repos and repo != '*'):
                errors.append(f'{tid}: invalid write scope {w}')
            if w.startswith('Plan:ledger/tasks/') and not re.fullmatch(r'Plan:ledger/tasks/[a-z0-9]+(?:-[a-z0-9]+)*\.md', w):
                errors.append(f'{tid}: ledger record {w} must use the lower-case hyphenated task key (DLV-26)')
        b = t.get('baseline', {})
        if b.get('state') not in BASELINE:
            errors.append(f'{tid}: invalid baseline state {b.get("state")}')
        if b.get('state') == 'accepted' and not b.get('evidence'):
            errors.append(f'{tid}: accepted baseline without evidence')
    for l in g.lanes.values():
        if l['repo'] not in g.repos and l['repo'] != 'multiple':
            errors.append(f'lane {l["id"]}: unknown repository {l["repo"]}')
    # Adoption slices: exactly one per (repository, lane) pair that has non-adoption tasks (DLV-22).
    pairs = {(t['repo'], t['lane']) for t in g.data['tasks'] if t.get('kind') != 'adoption'}
    seen_pairs = Counter((s['repo'], s['lane']) for s in g.slices.values())
    for sid, s in g.slices.items():
        if not SLICE_ID.match(sid):
            errors.append(f'{sid}: invalid adoption slice id')
        parent = g.repos.get(s.get('repo'), {}).get('adoptionTask')
        if s.get('adoptionTask') != parent or not sid.startswith(f'{parent}.') or sid != f'{parent}.{s.get("lane")}':
            errors.append(f'{sid}: slice does not belong to the adoption task of {s.get("repo")}')
        if s.get('lane') not in g.lanes:
            errors.append(f'{sid}: unknown lane {s.get("lane")}')
        if not s.get('title'):
            errors.append(f'{sid}: missing title')
    for pair in pairs:
        if g.repos.get(pair[0], {}).get('adoptionTask') and seen_pairs.get(pair, 0) != 1:
            errors.append(f'repository {pair[0]} lane {pair[1]}: expected exactly one adoption slice, found {seen_pairs.get(pair, 0)}')
    for pair in seen_pairs:
        if pair not in pairs:
            errors.append(f'adoption slice for {pair[0]}/{pair[1]} has no tasks')
    # Package acceptance is a roll-up, never a start barrier for work outside the package (DLV-35).
    accept = {t['id']: t['packageAcceptance'] for t in g.data['tasks'] if t.get('packageAcceptance')}
    for tid, wp in accept.items():
        if not re.match(r'^WP-\d{2}$', wp):
            errors.append(f'{tid}: invalid packageAcceptance {wp}')
    for t in g.data['tasks']:
        if t.get('kind') == 'release' or t.get('packageAcceptance'):
            continue
        for e in t.get('start', []):
            wp = accept.get(e.get('task'))
            if wp and not any(o['ref'].startswith((wp + '.', wp + ':')) for o in t.get('obligations', [])):
                errors.append(f'{t["id"]}: start prerequisite on package acceptance task {e["task"]} ({wp}); depend on the '
                              f'producing tasks or use a completion prerequisite (DLV-35)')
    _, stuck = g.event_order()
    if stuck:
        errors.append(f'unsatisfiable prerequisites (deadlock) among {len(stuck)} tasks: {stuck[:12]}')
    # Obligation coverage.
    om = g.obligation_map()
    for sid in g.catalogue:
        if sid not in om:
            errors.append(f'substep {sid} is not mapped to any task')
        elif len(om[sid]) > 1 and any(p.strip().lower() == 'full' for _, p in om[sid]):
            warnings.append(f'substep {sid} mapped by {len(om[sid])} tasks but one claims "full"')
    for pid in g.pobs:
        if pid not in om:
            errors.append(f'package obligation {pid} is not mapped to any task')
    for s in g.pobs.values():
        if not POB_ID.match(s['id']):
            errors.append(f'invalid package obligation id {s["id"]}')
    # Substitutes.
    users = defaultdict(list)
    for t in g.data['tasks']:
        for s in t.get('substitutes', []):
            users[s].append(t['id'])
    for sid, s in g.subs.items():
        if not SUB_ID.match(sid):
            errors.append(f'invalid substitute id {sid}')
        for f in ('standsInFor', 'contract', 'proves', 'realProducer', 'replacedBy', 'realEvidence'):
            if not s.get(f):
                errors.append(f'{sid}: missing {f}')
        if s.get('class') not in SUB_CLASSES:
            errors.append(f'{sid}: class must be value or behavior (DLV-18)')
        rp = s.get('realProducer', [])
        rp = rp if isinstance(rp, list) else [rp]
        rb = s.get('replacedBy')
        for p in rp:
            if p not in g.tasks:
                errors.append(f'{sid}: unknown real producer {p}')
        if rb not in g.tasks:
            errors.append(f'{sid}: unknown replacing task {rb}')
            continue
        anc = g.ancestors(rb)
        for p in rp:
            if p in g.tasks and p != rb and p not in anc:
                errors.append(f'{sid}: replacing task {rb} does not depend on real producer {p}')
        for u in users.get(sid, []):
            if u != rb and u not in anc:
                errors.append(f'{sid}: replacing task {rb} does not depend on consumer {u}')
        if not users.get(sid):
            warnings.append(f'{sid}: substitute not used by any task')
        if g.tasks[rb].get('kind') not in {'integration', 'acceptance', 'release', 'service', 'producer', 'feature'}:
            warnings.append(f'{sid}: replacing task {rb} has kind {g.tasks[rb].get("kind")}')
    # Shared resources.
    for rid, r in g.res.items():
        if not RES_ID.match(rid):
            errors.append(f'invalid shared resource id {rid}')
        if r.get('ownerRepo') not in g.repos and r.get('ownerRepo') not in {'multiple', 'workstation'}:
            errors.append(f'{rid}: unknown owner repository {r.get("ownerRepo")}')
        for f in ('kind', 'owner', 'protocol', 'title'):
            if not r.get(f):
                errors.append(f'{rid}: missing {f}')
    # The same exact file written by two unordered tasks must be a declared shared resource.
    # Different files inside one module directory are ordinary parallel work resolved by Git.
    by_repo = defaultdict(list)
    for t in g.data['tasks']:
        for w in t.get('writes', []):
            repo, path = w.split(':', 1)
            path = path.split(' (', 1)[0].strip()
            if '*' in path or path.endswith('/') or not path:
                continue
            by_repo[repo].append((t['id'], path))
    shared_of = {t['id']: {s['resource'] for s in t.get('shared', [])} for t in g.data['tasks']}
    for repo, items in by_repo.items():
        for i in range(len(items)):
            a, pa = items[i]
            for j in range(i + 1, len(items)):
                b, pb = items[j]
                if a == b:
                    continue
                if pa != pb:
                    continue
                if a in g.ancestors(b) or b in g.ancestors(a):
                    continue
                if shared_of[a] & shared_of[b]:
                    continue
                warnings.append(f'unordered write overlap {a} ~ {b} in {repo}: {pa} / {pb}')
    # Gates.
    for gate, rec in g.gates.items():
        for tid in rec.get('tasks', []):
            if tid not in g.tasks:
                errors.append(f'gate {gate}: unknown task {tid}')
    return errors, warnings

def weights(g: Graph):
    return {tid: SIZES[t['size']] for tid, t in g.tasks.items()}

def _event_weights(g: Graph, done):
    return {('D', t): (0 if t in done else SIZES[g.tasks[t]['size']]) for t in g.tasks} | {('C', t): 0 for t in g.tasks}

def critical_path(g: Graph, done: set[str] | None = None):
    """Longest weighted chain on the event graph; a task's work sits on its delivery event."""
    done = done or set()
    order, _ = g.event_order()
    adj = g.events()
    w = _event_weights(g, done)
    finish, prev = {}, {}
    for n in order:
        best, arg = 0, None
        for p in sorted(adj.get(n, ())):
            if finish.get(p, 0) > best:
                best, arg = finish[p], p
        finish[n] = best + w[n]
        prev[n] = arg
    end = max(sorted(finish), key=lambda k: finish[k])
    length = finish[end]
    path = []
    while end:
        if end[0] == 'D' and end[1] not in path:
            path.append(end[1])
        end = prev[end]
    return list(reversed(path)), length

def levels(g: Graph, done: set[str] | None = None):
    """Delivery level: longest chain of unfinished prerequisite deliveries before a task can be delivered."""
    done = done or set()
    order, _ = g.event_order()
    adj = g.events()
    lvl = {}
    for n in order:
        ps = [lvl[p] for p in adj.get(n, ()) if p in lvl]
        base = max(ps) if ps else 0
        lvl[n] = base + (1 if n[0] == 'D' and n[1] not in done else 0)
    return {t: lvl[('D', t)] for t in g.tasks}

def simulate(g: Graph, workers: int, done: set[str] | None = None):
    """List scheduling on the event graph. A worker is busy only while a task's own work runs;
    completion prerequisites delay completion, not the worker. Priority: longest remaining path.
    Repository merge, review and CI capacity are not modelled. Returns makespan in size units."""
    done = set(done or set())
    adj = g.events()
    w = {t: SIZES[g.tasks[t]['size']] for t in g.tasks}
    succ = defaultdict(set)
    for n, ps in adj.items():
        for p in ps:
            succ[p].add(n)
    order, _ = g.event_order()
    rem = {}
    for n in reversed(order):
        rem[n] = (w[n[1]] if n[0] == 'D' else 0) + max((rem[s] for s in succ.get(n, ())), default=0)
    reached = set()
    for t in done:
        reached.add(('D', t)); reached.add(('C', t))
    time, running, heap, queued = 0.0, [], [], set()

    def settle():
        changed = True
        while changed:
            changed = False
            for t in g.tasks:
                c = ('C', t)
                if c not in reached and ('D', t) in reached and adj[c] <= reached:
                    reached.add(c); changed = True
            for t in g.tasks:
                d = ('D', t)
                if d in reached or t in queued:
                    continue
                if adj.get(d, set()) <= reached:
                    heapq.heappush(heap, (-rem[d], t)); queued.add(t)

    settle()
    while len(reached) < 2 * len(g.tasks):
        while heap and (workers <= 0 or len(running) < workers):
            _, t = heapq.heappop(heap)
            heapq.heappush(running, (time + w[t], t))
        if not running:
            raise Fail('simulation deadlock (unsatisfiable prerequisites)')
        end, t = heapq.heappop(running)
        time = end
        reached.add(('D', t))
        settle()
    return time

def old_model_metrics(design: Path):
    """Depth of the retired WP-level graph and the retired serial substep count."""
    seq = (design / 'docs/planning/implementation-sequence.md').read_text(encoding='utf-8')
    return {'substeps': len(substeps(design))}

def analysis(g: Graph, worker_counts=(1, 2, 4, 8, 16, 32, 64, 0)):
    done = {tid for tid, t in g.tasks.items() if t['baseline']['state'] == 'accepted'}
    total = sum(SIZES[t['size']] for tid, t in g.tasks.items() if tid not in done)
    path, length = critical_path(g, done)
    lvl = levels(g, done)
    width = Counter(v for tid, v in lvl.items() if tid not in done)
    sims = {}
    for wk in worker_counts:
        sims['unbounded' if wk == 0 else str(wk)] = simulate(g, wk, done)
    edge_types = Counter()
    for t in g.tasks.values():
        for e in t.get('start', []):
            edge_types[e['type']] += 1
        for e in t.get('complete', []):
            edge_types['integration(completion)'] += 1
    adopted = done | {tid for tid, t in g.tasks.items() if t.get('kind') == 'adoption'}
    ready = [tid for tid, t in g.tasks.items() if tid not in done and t.get('kind') != 'adoption'
             and all(p in adopted for p in g.starts(tid))]
    # Concurrency inside each repository: tasks on the same delivery level have no prerequisite path
    # between them, so they can be in progress at the same time (subject to declared shared resources).
    per_repo = []
    for repo in sorted({t['repo'] for t in g.data['tasks'] if t.get('kind') != 'adoption'}):
        open_tasks = sorted(tid for tid, t in g.tasks.items()
                            if t['repo'] == repo and t.get('kind') != 'adoption' and tid not in done)
        if not open_tasks:
            continue
        by_level = Counter(lvl[tid] for tid in open_tasks)
        widest_level, widest = sorted(by_level.items(), key=lambda kv: (-kv[1], kv[0]))[0]
        at_level = [tid for tid in open_tasks if lvl[tid] == widest_level]
        examples, lanes_seen = [], set()
        for tid in at_level:
            if g.tasks[tid]['lane'] not in lanes_seen:
                examples.append(tid)
                lanes_seen.add(g.tasks[tid]['lane'])
        examples += [tid for tid in at_level if tid not in examples]
        per_repo.append({'repository': repo, 'openTasks': len(open_tasks),
                         'lanes': len({g.tasks[tid]['lane'] for tid in open_tasks}),
                         'widestLevel': widest_level, 'widestLevelTasks': widest,
                         'readyAfterAdoption': sorted(tid for tid in ready if g.tasks[tid]['repo'] == repo),
                         'examples': examples[:4]})
    return {
        'tasks': len(g.data['tasks']), 'adoptionSlices': len(g.slices), 'acceptedBaseline': len(done),
        'remainingWork': total, 'concurrencyByRepository': per_repo,
        'criticalPath': path, 'criticalPathLength': length,
        'maxLevel': max((v for tid, v in lvl.items() if tid not in done), default=0),
        'levelWidths': dict(sorted(width.items())),
        'maxLevelWidth': max(width.values()) if width else 0,
        'simulatedMakespan': sims, 'edgeTypes': dict(edge_types),
        'initialReady': sorted(ready),
    }

def md_escape(s: str) -> str:
    return (s or '').replace('|', '/').replace('\n', ' ').strip()

def task_link(g: Graph, tid: str, from_rel: str) -> str:
    import posixpath
    lane = g.tasks[tid]['lane']
    target = f'{DELIVERY_REL}/lanes/{lane}.md'
    rel = posixpath.relpath(target, str(Path(from_rel).parent.as_posix()))
    if target == from_rel:
        rel = ''
    return f'[{tid}]({rel}#{slug(tid)})'

def generated_header(from_rel: str) -> str:
    import posixpath
    graph = posixpath.relpath(GRAPH_REL, str(Path(from_rel).parent.as_posix()))
    model = posixpath.relpath(f'{DELIVERY_REL}/README.md', str(Path(from_rel).parent.as_posix()))
    return (f'> Generated from [the delivery graph]({graph}) by Plan `tools/delivery.py`; do not edit by hand. '
            f'Rules and definitions: [delivery model]({model}).\n')

def render_lane(g: Graph, lane: dict) -> str:
    rel = f'{DELIVERY_REL}/lanes/{lane["id"]}.md'
    L = Linker(g.design, rel)
    succ = g.succ_map()
    tasks = [t for t in g.data['tasks'] if t['lane'] == lane['id']]
    out = [f'# {lane["title"]} — delivery tasks', '', generated_header(rel)]
    out.append(L.text(lane.get('description', '')))
    out.append('')
    repos = sorted({t['repo'] for t in tasks})
    out.append(f'Tasks: {len(tasks)} · Owning repositories: {", ".join(repos)} · '
               f'Integration owner(s): {", ".join(g.repos[r]["integrationOwner"] for r in repos)}')
    out.append('')
    out.append('| Task | Title | Kind | Size | Start prerequisites | Baseline |')
    out.append('|---|---|---|---|---|---|')
    for t in tasks:
        pre = ', '.join(f'{task_link(g, e["task"], rel)} ({e["type"]})' for e in t['start']) or 'none'
        out.append(f'| {task_link(g, t["id"], rel)} | {md_escape(t["title"])} | {t["kind"]} | {t["size"]} | {pre} | '
                   f'{t["baseline"]["state"]} |')
    out.append('')
    out.append('## Tasks')
    out.append('')
    for t in tasks:
        out.append(f'<a id="{slug(t["id"])}"></a>')
        out.append('')
        out.append(f'### {t["id"]} — {md_escape(t["title"])}')
        out.append('')
        out.append(f'**Outcome.** {L.text(t["outcome"])}')
        out.append('')
        out.append('| Field | Value |')
        out.append('|---|---|')
        repo = g.repos[t['repo']]
        touches = ', '.join(t.get('alsoTouches', []))
        out.append(f'| Owning repository | {t["repo"]} (`{repo["root"]}`); integration owner: {repo["integrationOwner"]}, '
                   f'the holder of `roles/{key_of("integration-" + t["repo"])}`'
                   + (f'; also touches {touches}' if touches else '') + ' |')
        out.append(f'| Claim, branch and ledger | `claims/{key_of(t["id"])}` and ledger record `ledger/tasks/{key_of(t["id"])}.md` in '
                   f'the Plan repository; task branch `task/{key_of(t["id"])}` ([DLV-26](../README.md#rule-dlv-26)) |')
        out.append(f'| Kind / size | {t["kind"]} / {t["size"]}' + (' · early risk proof' if t.get('earlyRiskProof') else '') + ' |')
        if t.get('packageAcceptance'):
            out.append(f'| Package acceptance | Records the {L.link(t["packageAcceptance"])} acceptance receipt after every task mapped to the '
                       f'package; tasks outside the package never start from it ([DLV-35](../README.md#rule-dlv-35)) |')
        obl = '<br>'.join(f'{obligation_link(g, L, o["ref"])} — {L.text(o["part"])}' for o in t['obligations'])
        out.append(f'| Obligations | {obl} |')
        if t.get('provides'):
            out.append(f'| Provides | {L.text("; ".join(t["provides"]))} |')
        st = '<br>'.join(f'**{e["type"]}** {task_link(g, e["task"], rel)} — {L.text(e["need"])}. *Why:* {L.text(e["why"])}'
                         for e in t['start']) or 'none'
        out.append(f'| Start prerequisites | {st} |')
        ent = g.entry(t['id'])
        if ent:
            out.append(f'| Entry condition | {task_link(g, ent, rel)} — the adoption slice for this repository and lane is complete ([DLV-22](../README.md#rule-dlv-22)) |')
        cp = '<br>'.join(f'**{e["type"]}** {task_link(g, e["task"], rel)} — {L.text(e["need"])}. *Why:* {L.text(e["why"])}'
                         for e in t['complete']) or 'none'
        out.append(f'| Completion prerequisites | {cp} |')
        down = sorted(succ.get(t['id'], ()))
        out.append(f'| Unblocks | {", ".join(task_link(g, d, rel) for d in down) or "none"} |')
        if t.get('substitutes'):
            import posixpath
            srel = posixpath.relpath(f'{DELIVERY_REL}/substitutes.md', str(Path(rel).parent.as_posix()))
            subs = ', '.join(f'[{s}]({srel}#{s.lower()})' for s in t['substitutes'])
            out.append(f'| Permitted substitutes | {subs} |')
        out.append(f'| Write scope | {"<br>".join("`" + w + "`" for w in t["writes"])} |')
        if t.get('shared'):
            import posixpath
            rrel = posixpath.relpath(f'{DELIVERY_REL}/shared-resources.md', str(Path(rel).parent.as_posix()))
            sh = ', '.join(f'[{s["resource"]}]({rrel}#{s["resource"].lower()}) ({s["mode"]})' for s in t['shared'])
            out.append(f'| Shared resources | {sh} |')
        out.append(f'| Validation | {L.text(t["validation"])} |')
        out.append(f'| Completion evidence | {L.text(t["evidence"])} |')
        b = t['baseline']
        btxt = b['state'] + (f' — {L.text(b.get("evidence", ""))}' if b.get('evidence') else '') + \
            (f' {L.text(b.get("notes", ""))}' if b.get('notes') else '')
        out.append(f'| Baseline (unreviewed unless accepted) | {btxt} |')
        if t.get('notes'):
            out.append(f'| Notes | {L.text(t["notes"])} |')
        out.append('')
    if lane['id'] == 'adoption' and g.slices:
        out.append('## Adoption slices')
        out.append('')
        out.append('Each slice classifies the tasks of one repository and lane against the frozen baseline and, when it is '
                   'recorded, opens those tasks except the ones it classifies as inherited ([DLV-22](../README.md#rule-dlv-22)). '
                   'Slices are claimed and recorded separately (claim `claims/adopt-NN-<lane>`, record '
                   '`ledger/tasks/adopt-NN-<lane>.md`); one reviewed pull request may carry several. Every task a slice '
                   'classifies as inherited, including each accepted-baseline task in its scope, also gets its own record '
                   '`ledger/tasks/<key>.md` with `status: inherited` '
                   '([ledger records produced by adoption](../adoption.md#3-ledger-records-produced-by-adoption)) in the '
                   'same pull request as the slice record, so it never becomes ready; a task inherited with adjustment '
                   'opens with its remaining scope. The repository adoption task records the repository-wide '
                   'facts and closes after all of its slices.')
        out.append('')
        out.append('| Slice | Repository | Lane | Tasks it opens | Accepted baseline in scope | Repository record |')
        out.append('|---|---|---|---|---|---|')
        for sid in sorted(g.slices, key=lambda s: (g.slices[s]['adoptionTask'], s)):
            s = g.slices[sid]
            scope = g.slice_tasks(sid)
            accepted = [x for x in scope if g.tasks[x]['baseline']['state'] == 'accepted']
            opens = len(scope) - len(accepted)
            out.append(f'| <a id="{slug(sid)}"></a>{sid} | {s["repo"]} | [{md_escape(g.lanes[s["lane"]]["title"])}]({s["lane"]}.md) | '
                       f'{opens} | {", ".join(task_link(g, x, rel) for x in accepted) or "none"} | '
                       f'{task_link(g, s["adoptionTask"], rel)} |')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'

def obligation_link(g: Graph, L: Linker, ref: str) -> str:
    if SUBSTEP.match(ref) or DECISION.match(ref):
        return L.link(ref)
    m = POB_ID.match(ref)
    p = g.pobs[ref]
    return f'{L.link("WP-" + m[1])} {L.text(p["title"])}'

def render_traceability(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/traceability.md'
    L = Linker(g.design, rel)
    om = g.obligation_map()
    out = ['# Obligation Traceability', '', generated_header(rel),
           'Every active numbered substep and every package-level obligation maps to the delivery tasks that '
           'satisfy it. An obligation is satisfied only when every mapped task is complete with its recorded '
           'evidence; a mapped part never substitutes for the whole.', '']
    by_wp = defaultdict(list)
    for sid, s in g.catalogue.items():
        by_wp[s['wp']].append(sid)
    for wp in sorted(by_wp):
        f = wp_files(g.design)[wp]
        title = next((ln[2:].strip() for ln in f.read_text(encoding='utf-8').splitlines() if ln.startswith('# ')), wp)
        out.append(f'## {L.link("WP-" + wp)} — {md_escape(title.split("—", 1)[-1].strip())}')
        out.append('')
        out.append('| Obligation | Title | Delivery tasks (part) |')
        out.append('|---|---|---|')
        for sid in sorted(by_wp[wp]):
            tasks = '<br>'.join(f'{task_link(g, tid, rel)} ({L.text(part)})' for tid, part in om.get(sid, []))
            out.append(f'| {L.link(sid)} | {md_escape(g.catalogue[sid]["title"])} | {tasks} |')
        pobs = [p for p in g.pobs.values() if p['id'].startswith(f'WP-{wp}:')]
        for p in pobs:
            tasks = '<br>'.join(f'{task_link(g, tid, rel)} ({L.text(part)})' for tid, part in om.get(p['id'], []))
            out.append(f'| {L.link("WP-" + wp)} package obligation | {L.text(p["title"])} | {tasks} |')
        out.append('')
    out.append('## Gates')
    out.append('')
    out.append('| Gate | Contribution | Delivery tasks |')
    out.append('|---|---|---|')
    for gate in sorted(g.gates):
        rec = g.gates[gate]
        glabel = L.link(gate) if (L.home(gate) or CORPUS_ID.fullmatch(gate)) else f'[{gate}]({L.rel("docs/experience/03-state-and-acceptance.md")})'
        out.append(f'| {glabel} | {L.text(rec.get("contribution", ""))} | '
                   f'{", ".join(task_link(g, t, rel) for t in rec.get("tasks", []))} |')
    out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'

def render_substitutes(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/substitutes.md'
    L = Linker(g.design, rel)
    users = defaultdict(list)
    for t in g.data['tasks']:
        for s in t.get('substitutes', []):
            users[s].append(t['id'])
    out = ['# Substitutes and Real Replacement', '', generated_header(rel),
           'A substitute implements an authoritative contract so that a consumer can start before its real '
           'producer exists. Its checks prove only what is stated here. The replacing task removes runtime '
           'registration of the substitute and records the real evidence; retained regression fixtures stay '
           'test-only.', '',
           'A **value** substitute supplies contract-shaped data (vectors, documents, recorded responses) that only '
           "the consumer's own logic interprets; a **behavior** substitute emulates a producer's decisions or effects. "
           'Neither kind closes a service, authorization, transaction, hardware, provider, AI or commercial gate '
           '([DLV-18](README.md#rule-dlv-18)).', '',
           '| Substitute | Class | Stands in for | Real producer | Replaced by | Used by |', '|---|---|---|---|---|---|']
    for sid in sorted(g.subs):
        s = g.subs[sid]
        rp = s['realProducer'] if isinstance(s['realProducer'], list) else [s['realProducer']]
        out.append(f'| [{sid}](#{sid.lower()}) | {s["class"]} | {L.text(s["standsInFor"])} | '
                   f'{", ".join(task_link(g, p, rel) for p in rp)} | {task_link(g, s["replacedBy"], rel)} | '
                   f'{", ".join(task_link(g, u, rel) for u in users.get(sid, []))} |')
    out.append('')
    for sid in sorted(g.subs):
        s = g.subs[sid]
        out.append(f'### {sid}')
        out.append('')
        out.append('| Field | Value |')
        out.append('|---|---|')
        out.append(f'| Class | {s["class"]} |')
        out.append(f'| Stands in for | {L.text(s["standsInFor"])} |')
        out.append(f'| Authoritative contract | {L.text(s["contract"])} |')
        out.append(f'| What its checks prove | {L.text(s["proves"])} |')
        out.append(f'| What it does not prove | {L.text(s.get("doesNotProve", "Any real runtime, provider, device, integration or commercial behavior."))} |')
        rp = s['realProducer'] if isinstance(s['realProducer'], list) else [s['realProducer']]
        out.append(f'| Real producer | {", ".join(task_link(g, p, rel) for p in rp)} |')
        out.append(f'| Removes runtime substitution | {task_link(g, s["replacedBy"], rel)} |')
        out.append(f'| Real evidence still required | {L.text(s["realEvidence"])} |')
        if s.get('origin'):
            out.append(f'| Origin | {L.text(s["origin"])} |')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'

def render_resources(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/shared-resources.md'
    L = Linker(g.design, rel)
    touch = defaultdict(list)
    for t in g.data['tasks']:
        for s in t.get('shared', []):
            touch[s['resource']].append((t['id'], s['mode']))
    out = ['# Shared Resources and Write Ownership', '', generated_header(rel),
           'Each shared file, registry, sequence, environment, key or pointer has exactly one owning role. '
           'Tasks declare how they touch it; the owner applies the protocol. Independent worktrees do not '
           'remove semantic conflicts, so these declarations are part of task readiness and merge review. '
           'A protocol that names an exclusive phase (a live run in a deployed environment, a heavy local build) '
           'binds every task that enters that phase, for that phase only, whatever mode the task declares for its '
           'other edits ([DLV-11](README.md#rule-dlv-11)).', '']
    out.append('| Resource | Kind | Owner | Tasks (mode) |')
    out.append('|---|---|---|---|')
    for rid in sorted(g.res):
        r = g.res[rid]
        tasks = ', '.join(f'{task_link(g, t, rel)} ({m})' for t, m in touch.get(rid, []))
        out.append(f'| [{rid}](#{rid.lower()}) | {r["kind"]} | {L.text(r["owner"])} | {tasks} |')
    out.append('')
    for rid in sorted(g.res):
        r = g.res[rid]
        out.append(f'<a id="{rid.lower()}"></a>')
        out.append('')
        out.append(f'### {rid} — {md_escape(r["title"])}')
        out.append('')
        out.append(f'Repository: {r["ownerRepo"]} · Kind: {r["kind"]} · Owner: {L.text(r["owner"])}')
        out.append('')
        out.append(f'**Protocol.** {L.text(r["protocol"])}')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'

def render_analysis(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/schedule-analysis.md'
    L = Linker(g.design, rel)
    a = analysis(g)
    out = ['# Schedule Analysis', '', generated_header(rel)]
    out.append(L.text(g.data.get('analysisPreamble', '')))
    out.append('')
    out.append('## Structural facts (computed from the graph)')
    out.append('')
    out.append('| Measure | Value |')
    out.append('|---|---|')
    out.append(f'| Delivery tasks | {a["tasks"]} ({a["acceptedBaseline"]} carried as accepted baseline), plus {a["adoptionSlices"]} adoption slices |')
    et = ', '.join(f'{k} {v}' for k, v in sorted(a['edgeTypes'].items()))
    out.append(f'| Dependency edges by type | {et} |')
    out.append(f'| Remaining work (size units: S=1, M=2, L=4, XL=8) | {a["remainingWork"]} |')
    out.append(f'| Longest dependency chain (levels) | {a["maxLevel"]} |')
    out.append(f'| Widest level (tasks whose longest prerequisite chain has equal length) | {a["maxLevelWidth"]} |')
    out.append(f'| Critical path length (size units) | {a["criticalPathLength"]} |')
    out.append(f'| Retired model | {len(g.catalogue)} numbered substeps advanced one at a time from a single Current task |')
    out.append('')
    out.append('## Work by lane')
    out.append('')
    out.append('| Lane | Tasks | Size units | Owning repositories |')
    out.append('|---|---|---|---|')
    for lane in g.data['lanes']:
        lt = [t for t in g.data['tasks'] if t['lane'] == lane['id']]
        if lt:
            out.append(f'| [{md_escape(lane["title"])}](lanes/{lane["id"]}.md) | {len(lt)} | {sum(SIZES[t["size"]] for t in lt)} | '
                       f'{", ".join(sorted({t["repo"] for t in lt}))} |')
    out.append('')
    out.append('## Concurrency inside each repository')
    out.append('')
    out.append('Tasks on the same delivery level have no prerequisite path between them, so they can be in progress '
               'at the same time in one repository, each in its own worktree and write scope, subject only to their '
               'declared shared resources. The counts are structural properties of the graph, not measured throughput.')
    out.append('')
    out.append('| Repository | Open tasks | Lanes | Widest level (tasks at once) | Ready after its adoption slices | Examples that can run at the same time |')
    out.append('|---|---|---|---|---|---|')
    for r in a['concurrencyByRepository']:
        ex = ', '.join(f'{task_link(g, t, rel)} {md_escape(g.tasks[t]["title"])}' for t in r['examples'])
        out.append(f'| {r["repository"]} | {r["openTasks"]} | {r["lanes"]} | level {r["widestLevel"]}: {r["widestLevelTasks"]} | '
                   f'{len(r["readyAfterAdoption"])} | {ex} |')
    out.append('')
    out.append('## Critical path')
    out.append('')
    out.append('| # | Task | Size | Title |')
    out.append('|---|---|---|---|')
    for i, tid in enumerate(a['criticalPath'], 1):
        t = g.tasks[tid]
        out.append(f'| {i} | {task_link(g, tid, rel)} | {t["size"]} | {md_escape(t["title"])} |')
    out.append('')
    out.append('## Level widths')
    out.append('')
    out.append('| Level | Tasks |')
    out.append('|---|---|')
    for k, v in a['levelWidths'].items():
        out.append(f'| {k} | {v} |')
    out.append('')
    out.append('## Simulated makespan (unmeasured estimate)')
    out.append('')
    out.append(L.text(g.data.get('simulationAssumptions', '')))
    out.append('')
    out.append('| Workers | Makespan (size units) | Estimated speed-up over one worker |')
    out.append('|---|---|---|')
    one = a['simulatedMakespan']['1']
    for k, v in a['simulatedMakespan'].items():
        out.append(f'| {k} | {v:g} | {(one / v if v else 1):.1f}× |')
    out.append('')
    out.append('## Provisional initial ready set')
    out.append('')
    out.append(L.text(g.data.get('readySetNote', '')))
    out.append('')
    out.append(', '.join(task_link(g, t, rel) for t in a['initialReady']))
    out.append('')
    if g.data.get('bottlenecks'):
        out.append('## Remaining serial dependencies and bottlenecks')
        out.append('')
        for b in g.data['bottlenecks']:
            out.append(f'- **{md_escape(b["title"])}.** {L.text(b["text"])}')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'

def render_wp_block(g: Graph, wp: str, rel: str) -> str:
    L = Linker(g.design, rel)
    mapped = defaultdict(list)
    for t in g.data['tasks']:
        for o in t['obligations']:
            m = SUBSTEP.match(o['ref']) or POB_ID.match(o['ref'])
            if m and m[1] == wp:
                mapped[t['id']].append(o)
    own = sorted(mapped, key=lambda x: (g.tasks[x]['lane'], x))
    lines = [BEGIN, '',
             'Scheduling is task-level under [P2-018](../../decisions/phase-2-specification-decisions.md#rule-p2-018). '
             'This package is an obligation set; it is satisfied when every task below is complete with its evidence. '
             'Prerequisites are typed task edges, never "all upstream packages complete".', '',
             '| Delivery task | Satisfies | Start prerequisites outside this package |', '|---|---|---|']
    own_set = set(own)
    for tid in own:
        t = g.tasks[tid]
        sat = '<br>'.join(f'{obligation_link(g, L, o["ref"])} ({L.text(o["part"])})' for o in mapped[tid])
        ext = ', '.join(f'{task_link(g, e["task"], rel)} ({e["type"]})' for e in t['start'] if e['task'] not in own_set) or 'none'
        lines.append(f'| {task_link(g, tid, rel)} | {sat} | {ext} |')
    succ = g.succ_map()
    consumers = sorted({s for tid in own for s in succ.get(tid, ()) if s not in own_set})
    lines.append('')
    lines.append('**Consumers outside this package:** ' + (', '.join(task_link(g, c, rel) for c in consumers) or 'none') + '.')
    lines.append('')
    lines.append(END)
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(lines)

def splice(text: str, block: str) -> str:
    if BEGIN in text:
        pre, rest = text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        return pre + block + post
    raise Fail('missing generated delivery block markers')

def design_views(g):
    """Render only the Design-owned views, using the canonical Plan algorithms."""
    result = {}
    for lane in g.data['lanes']:
        if any(t['lane'] == lane['id'] for t in g.data['tasks']):
            result[f'{DELIVERY_REL}/lanes/{lane["id"]}.md'] = render_lane(g, lane)
    for name, renderer in [('traceability', render_traceability), ('substitutes', render_substitutes),
                           ('shared-resources', render_resources), ('schedule-analysis', render_analysis)]:
        result[f'{DELIVERY_REL}/{name}.md'] = renderer(g)
    for wp, path in wp_files(g.design).items():
        text = path.read_text(encoding='utf-8')
        if BEGIN in text:
            relative = path.relative_to(g.design).as_posix()
            result[relative] = splice(text, render_wp_block(g, wp, relative))
    return result


def graph(root, docs=None):
    """Fail closed on malformed graph, stale views, and work-package structure."""
    docs = corpus.load(root) if docs is None else docs
    result = {'nodes': 0, 'edges': 0, 'activePackages': [], 'packages': {}, 'errors': []}
    try:
        data = load_json(root / GRAPH_REL)
        if data.get('schemaVersion') != 1 or type(data.get('schemaVersion')) is not int:
            raise ValueError('unsupported delivery graph schema')
        for name in ('tasks', 'lanes', 'repositories', 'adoptionSlices', 'substitutes', 'sharedResources', 'packageObligations'):
            rows = data.get(name)
            if not isinstance(rows, list) or any(not isinstance(row, dict) for row in rows):
                raise ValueError(f'{name}: expected record array')
            ids = [row['id'] for row in rows]
            if len(ids) != len(set(ids)):
                raise ValueError(f'{name}: duplicate identifier')
        allowed = {'DesktopPlatform', 'Contracts', 'ArcScope', 'Cloud', 'AI', 'Web', 'Mobile', 'Design', 'Plan'}
        if any(row['id'] not in allowed for row in data['repositories']):
            raise ValueError('unknown repository in delivery graph')
        # The caller can supply mutated documents for independent rejection fixtures.
        # Materialize data only; no code, hooks, or subprocesses run from this tree.
        with tempfile.TemporaryDirectory(prefix='arcforges-graph-docs-') as temporary:
            snapshot = Path(temporary)
            for name, text in docs.items():
                target = snapshot / name
                if not target.resolve().is_relative_to(snapshot.resolve()):
                    raise ValueError('documentation path escapes graph snapshot')
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(text, encoding='utf-8', newline='\n')
            target = snapshot / GRAPH_REL
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(json.dumps(data), encoding='utf-8')
            model = Graph(snapshot)
            errors, warnings = validate(model)
            result['errors'].extend(errors)
            result['warnings'] = warnings
            active = {match[1] for task in model.data['tasks'] for obligation in task['obligations']
                      if (match := re.match(r'WP-(\d{2})[.:]', obligation['ref']))}
            result.update(nodes=len(model.tasks), edges=sum(len(model.starts(t)) + len(model.complete_edges(v))
                          for t, v in model.tasks.items()), activePackages=sorted(active))
            for name, text in docs.items():
                numbers = re.findall(r'^## (\d+(?:\.\d+)*)(?:\.)?\s', text, re.M)
                if len(numbers) != len(set(numbers)):
                    result['errors'].append([name, 'duplicate numbered section'])
                match = re.match(r'docs/planning/work-packages/(\d{2})-', name)
                if not match or match[1] not in active:
                    continue
                key = match[1]
                if key in result['packages']:
                    result['errors'].append([name, 'duplicate package identifier', key])
                result['packages'][key] = name
                if set(numbers) != {str(i) for i in range(1, 10)}:
                    result['errors'].append([name, 'mandatory sections'])
                evidence = text.split('## 7. ', 1)[-1].split('\n## ', 1)[0]
                rows = [line for line in evidence.splitlines() if line.startswith('|') and f'#rule-wp-{key}.90)' in line]
                if len(rows) != 1:
                    result['errors'].append([name, 'owned .90 evidence rows', len(rows)])
                if BEGIN not in text or END not in text:
                    result['errors'].append([name, 'missing generated package view'])
            if set(result['packages']) != active:
                result['errors'].append(['active package owner has no work-package source'])
            if not errors:
                generated = design_views(model)
                for name, expected in generated.items():
                    if docs.get(name) != expected:
                        result['errors'].append([name, 'generated view drift'])
                result['generatedViews'] = len(generated)
    except (OSError, ValueError, KeyError, TypeError, IndexError, AttributeError, RecursionError) as error:
        result['errors'].append([GRAPH_REL, str(error)])
    return result
