<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ArcSlate.Application</AssemblyName>
    <RootNamespace>ArcSlate.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\ArcForges.Application.Abstractions\ArcForges.Application.Abstractions.csproj" />
    <ProjectReference Include="..\ArcSlate.Domain\ArcSlate.Domain.csproj" />
  </ItemGroup>
</Project>
