// SPDX-License-Identifier: AGPL-3.0-only

using System.Text.Json.Serialization;
using ArcForges.Contracts.LocalRpc.Notes;
using ArcForges.Contracts.LocalRpc.Scope;
using ArcForges.Contracts.LocalRpc.Slate;

namespace ArcForges.Contracts.LocalRpc;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = false,
    AllowDuplicateProperties = false,
    RespectNullableAnnotations = true,
    RespectRequiredConstructorParameters = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
// Hub
[JsonSerializable(typeof(RegisterInstanceRequest))]
[JsonSerializable(typeof(RegisterInstanceResult))]
[JsonSerializable(typeof(UnregisterInstanceRequest))]
[JsonSerializable(typeof(HeartbeatRequest))]
[JsonSerializable(typeof(HeartbeatResult))]
[JsonSerializable(typeof(DiscoverRequest))]
[JsonSerializable(typeof(DiscoverResult))]
[JsonSerializable(typeof(RouteRequest))]
[JsonSerializable(typeof(RouteResult))]
[JsonSerializable(typeof(RequestApprovalRequest))]
[JsonSerializable(typeof(RequestApprovalResult))]
[JsonSerializable(typeof(ResolveApprovalRequest))]
[JsonSerializable(typeof(ResolveApprovalResult))]
[JsonSerializable(typeof(CapabilityDescriptor))]
[JsonSerializable(typeof(ProviderRecord))]
// Events
[JsonSerializable(typeof(ConnectionEstablishedNotice))]
[JsonSerializable(typeof(ConnectionLostNotice))]
[JsonSerializable(typeof(ProviderHealthNotice))]
// Common
[JsonSerializable(typeof(SecurityPrincipalDto))]
[JsonSerializable(typeof(ActorChainEntryDto))]
[JsonSerializable(typeof(InvocationCorrelationDto))]
[JsonSerializable(typeof(ActorContextDto))]
[JsonSerializable(typeof(ProductActivityRefDto))]
[JsonSerializable(typeof(ProductActivitySnapshotDto))]
[JsonSerializable(typeof(TypedAnchorDto))]
[JsonSerializable(typeof(RationalDto))]
[JsonSerializable(typeof(LocalOutputTargetDto))]
[JsonSerializable(typeof(MutationStatus))]
// ArcNotes Requests & Responses
[JsonSerializable(typeof(SearchDocumentsRequest))]
[JsonSerializable(typeof(SearchDocumentsResponse))]
[JsonSerializable(typeof(ArcResult<SearchDocumentsResponse>))]
[JsonSerializable(typeof(FindByTagRequest))]
[JsonSerializable(typeof(FindByTagResponse))]
[JsonSerializable(typeof(ArcResult<FindByTagResponse>))]
[JsonSerializable(typeof(FindByPropertyRequest))]
[JsonSerializable(typeof(FindByPropertyResponse))]
[JsonSerializable(typeof(ArcResult<FindByPropertyResponse>))]
[JsonSerializable(typeof(GetDocumentSummaryRequest))]
[JsonSerializable(typeof(GetDocumentSummaryResponse))]
[JsonSerializable(typeof(ArcResult<GetDocumentSummaryResponse>))]
[JsonSerializable(typeof(GetDocumentMetadataRequest))]
[JsonSerializable(typeof(GetDocumentMetadataResponse))]
[JsonSerializable(typeof(ArcResult<GetDocumentMetadataResponse>))]
[JsonSerializable(typeof(ReadDocumentRequest))]
[JsonSerializable(typeof(ReadDocumentResponse))]
[JsonSerializable(typeof(ArcResult<ReadDocumentResponse>))]
[JsonSerializable(typeof(ReadBlocksRequest))]
[JsonSerializable(typeof(ReadBlocksResponse))]
[JsonSerializable(typeof(ArcResult<ReadBlocksResponse>))]
[JsonSerializable(typeof(ReadSelectionRequest))]
[JsonSerializable(typeof(ReadSelectionResponse))]
[JsonSerializable(typeof(ArcResult<ReadSelectionResponse>))]
[JsonSerializable(typeof(CreateDocumentRequest))]
[JsonSerializable(typeof(CreateDocumentResponse))]
[JsonSerializable(typeof(ArcResult<CreateDocumentResponse>))]
[JsonSerializable(typeof(CreateFromArtifactRequest))]
[JsonSerializable(typeof(CreateFromArtifactResponse))]
[JsonSerializable(typeof(ArcResult<CreateFromArtifactResponse>))]
[JsonSerializable(typeof(InsertBlocksRequest))]
[JsonSerializable(typeof(InsertBlocksResponse))]
[JsonSerializable(typeof(ArcResult<InsertBlocksResponse>))]
[JsonSerializable(typeof(ReplaceBlocksRequest))]
[JsonSerializable(typeof(ReplaceBlocksResponse))]
[JsonSerializable(typeof(ArcResult<ReplaceBlocksResponse>))]
[JsonSerializable(typeof(AppendBlocksRequest))]
[JsonSerializable(typeof(AppendBlocksResponse))]
[JsonSerializable(typeof(ArcResult<AppendBlocksResponse>))]
[JsonSerializable(typeof(UpdatePropertiesRequest))]
[JsonSerializable(typeof(UpdatePropertiesResponse))]
[JsonSerializable(typeof(ArcResult<UpdatePropertiesResponse>))]
[JsonSerializable(typeof(AddTagsRequest))]
[JsonSerializable(typeof(AddTagsResponse))]
[JsonSerializable(typeof(ArcResult<AddTagsResponse>))]
[JsonSerializable(typeof(MoveDocumentRequest))]
[JsonSerializable(typeof(MoveDocumentResponse))]
[JsonSerializable(typeof(ArcResult<MoveDocumentResponse>))]
[JsonSerializable(typeof(LinkDocumentsRequest))]
[JsonSerializable(typeof(LinkDocumentsResponse))]
[JsonSerializable(typeof(ArcResult<LinkDocumentsResponse>))]
[JsonSerializable(typeof(OpenArtifactRequest))]
[JsonSerializable(typeof(OpenArtifactResponse))]
[JsonSerializable(typeof(ArcResult<OpenArtifactResponse>))]
[JsonSerializable(typeof(ImportRequest))]
[JsonSerializable(typeof(ImportResponse))]
[JsonSerializable(typeof(ArcResult<ImportResponse>))]
[JsonSerializable(typeof(ExportRequest))]
[JsonSerializable(typeof(ExportResponse))]
[JsonSerializable(typeof(ArcResult<ExportResponse>))]
[JsonSerializable(typeof(TrashDocumentRequest))]
[JsonSerializable(typeof(TrashDocumentResponse))]
[JsonSerializable(typeof(ArcResult<TrashDocumentResponse>))]
[JsonSerializable(typeof(DeleteDocumentPermanentRequest))]
[JsonSerializable(typeof(DeleteDocumentPermanentResponse))]
[JsonSerializable(typeof(ArcResult<DeleteDocumentPermanentResponse>))]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Notes.GetContextRequest), TypeInfoPropertyName = "NotesGetContextRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Notes.GetContextResponse), TypeInfoPropertyName = "NotesGetContextResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Notes.GetContextResponse>), TypeInfoPropertyName = "ArcResultNotesGetContextResponse")]
// ArcScope Requests & Responses
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Scope.SearchResourcesRequest), TypeInfoPropertyName = "ScopeSearchResourcesRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Scope.SearchResourcesResponse), TypeInfoPropertyName = "ScopeSearchResourcesResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Scope.SearchResourcesResponse>), TypeInfoPropertyName = "ArcResultScopeSearchResourcesResponse")]
[JsonSerializable(typeof(ListSessionsRequest))]
[JsonSerializable(typeof(ListSessionsResponse))]
[JsonSerializable(typeof(ArcResult<ListSessionsResponse>))]
[JsonSerializable(typeof(QuerySignalRangeRequest))]
[JsonSerializable(typeof(QuerySignalRangeResponse))]
[JsonSerializable(typeof(ArcResult<QuerySignalRangeResponse>))]
[JsonSerializable(typeof(StartCaptureRequest))]
[JsonSerializable(typeof(StartCaptureResponse))]
[JsonSerializable(typeof(ArcResult<StartCaptureResponse>))]
[JsonSerializable(typeof(StopCaptureRequest))]
[JsonSerializable(typeof(StopCaptureResponse))]
[JsonSerializable(typeof(ArcResult<StopCaptureResponse>))]
[JsonSerializable(typeof(PauseCaptureRequest))]
[JsonSerializable(typeof(PauseCaptureResponse))]
[JsonSerializable(typeof(ArcResult<PauseCaptureResponse>))]
[JsonSerializable(typeof(ResumeCaptureRequest))]
[JsonSerializable(typeof(ResumeCaptureResponse))]
[JsonSerializable(typeof(ArcResult<ResumeCaptureResponse>))]
[JsonSerializable(typeof(GetCaptureStatusRequest))]
[JsonSerializable(typeof(GetCaptureStatusResponse))]
[JsonSerializable(typeof(ArcResult<GetCaptureStatusResponse>))]
[JsonSerializable(typeof(ListDecodersRequest))]
[JsonSerializable(typeof(ListDecodersResponse))]
[JsonSerializable(typeof(ArcResult<ListDecodersResponse>))]
[JsonSerializable(typeof(DecodeRangeRequest))]
[JsonSerializable(typeof(DecodeRangeResponse))]
[JsonSerializable(typeof(ArcResult<DecodeRangeResponse>))]
[JsonSerializable(typeof(GetDecoderErrorsRequest))]
[JsonSerializable(typeof(GetDecoderErrorsResponse))]
[JsonSerializable(typeof(ArcResult<GetDecoderErrorsResponse>))]
[JsonSerializable(typeof(ListPortsRequest))]
[JsonSerializable(typeof(ListPortsResponse))]
[JsonSerializable(typeof(ArcResult<ListPortsResponse>))]
[JsonSerializable(typeof(TestConnectionRequest))]
[JsonSerializable(typeof(TestConnectionResponse))]
[JsonSerializable(typeof(ArcResult<TestConnectionResponse>))]
[JsonSerializable(typeof(ConnectRequest))]
[JsonSerializable(typeof(ConnectResponse))]
[JsonSerializable(typeof(ArcResult<ConnectResponse>))]
[JsonSerializable(typeof(DisconnectRequest))]
[JsonSerializable(typeof(DisconnectResponse))]
[JsonSerializable(typeof(ArcResult<DisconnectResponse>))]
[JsonSerializable(typeof(GetConnectionsRequest))]
[JsonSerializable(typeof(GetConnectionsResponse))]
[JsonSerializable(typeof(ArcResult<GetConnectionsResponse>))]
[JsonSerializable(typeof(PauseViewRequest))]
[JsonSerializable(typeof(PauseViewResponse))]
[JsonSerializable(typeof(ArcResult<PauseViewResponse>))]
[JsonSerializable(typeof(ResumeViewRequest))]
[JsonSerializable(typeof(ResumeViewResponse))]
[JsonSerializable(typeof(ArcResult<ResumeViewResponse>))]
[JsonSerializable(typeof(GetLiveStateRequest))]
[JsonSerializable(typeof(GetLiveStateResponse))]
[JsonSerializable(typeof(ArcResult<GetLiveStateResponse>))]
[JsonSerializable(typeof(ListFindingsRequest))]
[JsonSerializable(typeof(ListFindingsResponse))]
[JsonSerializable(typeof(ArcResult<ListFindingsResponse>))]
[JsonSerializable(typeof(PreviewAnalysisRequest))]
[JsonSerializable(typeof(PreviewAnalysisResponse))]
[JsonSerializable(typeof(ArcResult<PreviewAnalysisResponse>))]
[JsonSerializable(typeof(RunAnalysisRequest))]
[JsonSerializable(typeof(RunAnalysisResponse))]
[JsonSerializable(typeof(ArcResult<RunAnalysisResponse>))]
[JsonSerializable(typeof(CreateAnnotationRequest))]
[JsonSerializable(typeof(CreateAnnotationResponse))]
[JsonSerializable(typeof(ArcResult<CreateAnnotationResponse>))]
[JsonSerializable(typeof(GenerateReportRequest))]
[JsonSerializable(typeof(GenerateReportResponse))]
[JsonSerializable(typeof(ArcResult<GenerateReportResponse>))]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Scope.StartExportRequest), TypeInfoPropertyName = "ScopeStartExportRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Scope.StartExportResponse), TypeInfoPropertyName = "ScopeStartExportResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Scope.StartExportResponse>), TypeInfoPropertyName = "ArcResultScopeStartExportResponse")]
[JsonSerializable(typeof(GetExportStatusRequest))]
[JsonSerializable(typeof(GetExportStatusResponse))]
[JsonSerializable(typeof(ArcResult<GetExportStatusResponse>))]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Scope.GetContextRequest), TypeInfoPropertyName = "ScopeGetContextRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Scope.GetContextResponse), TypeInfoPropertyName = "ScopeGetContextResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Scope.GetContextResponse>), TypeInfoPropertyName = "ArcResultScopeGetContextResponse")]
// ArcSlate Requests & Responses
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Slate.SearchResourcesRequest), TypeInfoPropertyName = "SlateSearchResourcesRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Slate.SearchResourcesResponse), TypeInfoPropertyName = "SlateSearchResourcesResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Slate.SearchResourcesResponse>), TypeInfoPropertyName = "ArcResultSlateSearchResourcesResponse")]
[JsonSerializable(typeof(GetProjectSnapshotRequest))]
[JsonSerializable(typeof(GetProjectSnapshotResponse))]
[JsonSerializable(typeof(ArcResult<GetProjectSnapshotResponse>))]
[JsonSerializable(typeof(SaveProjectRequest))]
[JsonSerializable(typeof(SaveProjectResponse))]
[JsonSerializable(typeof(ArcResult<SaveProjectResponse>))]
[JsonSerializable(typeof(LoadProjectRequest))]
[JsonSerializable(typeof(LoadProjectResponse))]
[JsonSerializable(typeof(ArcResult<LoadProjectResponse>))]
[JsonSerializable(typeof(UndoRequest))]
[JsonSerializable(typeof(UndoResponse))]
[JsonSerializable(typeof(ArcResult<UndoResponse>))]
[JsonSerializable(typeof(RedoRequest))]
[JsonSerializable(typeof(RedoResponse))]
[JsonSerializable(typeof(ArcResult<RedoResponse>))]
[JsonSerializable(typeof(JumpToRequest))]
[JsonSerializable(typeof(JumpToResponse))]
[JsonSerializable(typeof(ArcResult<JumpToResponse>))]
[JsonSerializable(typeof(ListRecoveriesRequest))]
[JsonSerializable(typeof(ListRecoveriesResponse))]
[JsonSerializable(typeof(ArcResult<ListRecoveriesResponse>))]
[JsonSerializable(typeof(OpenRecoveryRequest))]
[JsonSerializable(typeof(OpenRecoveryResponse))]
[JsonSerializable(typeof(ArcResult<OpenRecoveryResponse>))]
[JsonSerializable(typeof(CreateCheckpointRequest))]
[JsonSerializable(typeof(CreateCheckpointResponse))]
[JsonSerializable(typeof(ArcResult<CreateCheckpointResponse>))]
[JsonSerializable(typeof(ImportMediaRequest))]
[JsonSerializable(typeof(ImportMediaResponse))]
[JsonSerializable(typeof(ArcResult<ImportMediaResponse>))]
[JsonSerializable(typeof(GetAssetRequest))]
[JsonSerializable(typeof(GetAssetResponse))]
[JsonSerializable(typeof(ArcResult<GetAssetResponse>))]
[JsonSerializable(typeof(ListAssetsRequest))]
[JsonSerializable(typeof(ListAssetsResponse))]
[JsonSerializable(typeof(ArcResult<ListAssetsResponse>))]
[JsonSerializable(typeof(RelinkAssetRequest))]
[JsonSerializable(typeof(RelinkAssetResponse))]
[JsonSerializable(typeof(ArcResult<RelinkAssetResponse>))]
[JsonSerializable(typeof(GetImportStatusRequest))]
[JsonSerializable(typeof(GetImportStatusResponse))]
[JsonSerializable(typeof(ArcResult<GetImportStatusResponse>))]
[JsonSerializable(typeof(GetSequenceRequest))]
[JsonSerializable(typeof(GetSequenceResponse))]
[JsonSerializable(typeof(ArcResult<GetSequenceResponse>))]
[JsonSerializable(typeof(InsertClipRequest))]
[JsonSerializable(typeof(InsertClipResponse))]
[JsonSerializable(typeof(ArcResult<InsertClipResponse>))]
[JsonSerializable(typeof(MoveClipRequest))]
[JsonSerializable(typeof(MoveClipResponse))]
[JsonSerializable(typeof(ArcResult<MoveClipResponse>))]
[JsonSerializable(typeof(TrimClipRequest))]
[JsonSerializable(typeof(TrimClipResponse))]
[JsonSerializable(typeof(ArcResult<TrimClipResponse>))]
[JsonSerializable(typeof(SplitClipRequest))]
[JsonSerializable(typeof(SplitClipResponse))]
[JsonSerializable(typeof(ArcResult<SplitClipResponse>))]
[JsonSerializable(typeof(DeleteClipRequest))]
[JsonSerializable(typeof(DeleteClipResponse))]
[JsonSerializable(typeof(ArcResult<DeleteClipResponse>))]
[JsonSerializable(typeof(RippleDeleteRequest))]
[JsonSerializable(typeof(RippleDeleteResponse))]
[JsonSerializable(typeof(ArcResult<RippleDeleteResponse>))]
[JsonSerializable(typeof(ExtractRequest))]
[JsonSerializable(typeof(ExtractResponse))]
[JsonSerializable(typeof(ArcResult<ExtractResponse>))]
[JsonSerializable(typeof(RippleTrimRequest))]
[JsonSerializable(typeof(RippleTrimResponse))]
[JsonSerializable(typeof(ArcResult<RippleTrimResponse>))]
[JsonSerializable(typeof(RollRequest))]
[JsonSerializable(typeof(RollResponse))]
[JsonSerializable(typeof(ArcResult<RollResponse>))]
[JsonSerializable(typeof(SlipRequest))]
[JsonSerializable(typeof(SlipResponse))]
[JsonSerializable(typeof(ArcResult<SlipResponse>))]
[JsonSerializable(typeof(SlideRequest))]
[JsonSerializable(typeof(SlideResponse))]
[JsonSerializable(typeof(ArcResult<SlideResponse>))]
[JsonSerializable(typeof(LinkClipsRequest))]
[JsonSerializable(typeof(LinkClipsResponse))]
[JsonSerializable(typeof(ArcResult<LinkClipsResponse>))]
[JsonSerializable(typeof(UnlinkClipsRequest))]
[JsonSerializable(typeof(UnlinkClipsResponse))]
[JsonSerializable(typeof(ArcResult<UnlinkClipsResponse>))]
[JsonSerializable(typeof(AddMarkerRequest))]
[JsonSerializable(typeof(AddMarkerResponse))]
[JsonSerializable(typeof(ArcResult<AddMarkerResponse>))]
[JsonSerializable(typeof(MoveMarkerRequest))]
[JsonSerializable(typeof(MoveMarkerResponse))]
[JsonSerializable(typeof(ArcResult<MoveMarkerResponse>))]
[JsonSerializable(typeof(SetInOutRequest))]
[JsonSerializable(typeof(SetInOutResponse))]
[JsonSerializable(typeof(ArcResult<SetInOutResponse>))]
[JsonSerializable(typeof(PreviewEditRequest))]
[JsonSerializable(typeof(PreviewEditResponse))]
[JsonSerializable(typeof(ArcResult<PreviewEditResponse>))]
[JsonSerializable(typeof(ApplyEditRequest))]
[JsonSerializable(typeof(ApplyEditResponse))]
[JsonSerializable(typeof(ArcResult<ApplyEditResponse>))]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Slate.StartExportRequest), TypeInfoPropertyName = "SlateStartExportRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Slate.StartExportResponse), TypeInfoPropertyName = "SlateStartExportResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Slate.StartExportResponse>), TypeInfoPropertyName = "ArcResultSlateStartExportResponse")]
[JsonSerializable(typeof(GetExportRequest))]
[JsonSerializable(typeof(GetExportResponse))]
[JsonSerializable(typeof(ArcResult<GetExportResponse>))]
[JsonSerializable(typeof(CancelExportRequest))]
[JsonSerializable(typeof(CancelExportResponse))]
[JsonSerializable(typeof(ArcResult<CancelExportResponse>))]
[JsonSerializable(typeof(GetArtifactRequest))]
[JsonSerializable(typeof(GetArtifactResponse))]
[JsonSerializable(typeof(ArcResult<GetArtifactResponse>))]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Slate.GetContextRequest), TypeInfoPropertyName = "SlateGetContextRequest")]
[JsonSerializable(typeof(ArcForges.Contracts.LocalRpc.Slate.GetContextResponse), TypeInfoPropertyName = "SlateGetContextResponse")]
[JsonSerializable(typeof(ArcResult<ArcForges.Contracts.LocalRpc.Slate.GetContextResponse>), TypeInfoPropertyName = "ArcResultSlateGetContextResponse")]
public sealed partial class LocalRpcJsonContext : JsonSerializerContext
{
}
