# SPDX-License-Identifier: AGPL-3.0-only
"""Create (or refresh after a rebase) the immutable GOV.30 dependency-admission successor.

GOV.30 removes the osx-x64 and osx-arm64 RIDs (P2-023) from the desktop RID set. The two runtime.osx-*
ILCompiler coordinates admitted for those RIDs leave the closure; every other coordinate, version, content
hash and source record is kept. It chains from the receipt that is ACTIVE on the base branch and rebinds
every dependency input hash. Run it again after every rebase: the predecessor is read from the policy (or,
when this receipt is already active, from its own previousReceipt), so it never chains from itself.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "eng"))
import dependency_policy  # noqa: E402


RECEIPT = "eng/policy/dependency-reviews/gov-30-r1.json"
# The main commit the successor is reviewed against; update together with a rebase.
BASELINE_COMMIT = "f833de3410183d8c59b17ec54229e06ad1370d98"
REMOVED_COORDINATES = (
    "runtime.osx-arm64.microsoft.dotnet.ilcompiler/10.0.11",
    "runtime.osx-x64.microsoft.dotnet.ilcompiler/10.0.11",
)


def main() -> None:
    policy_path = ROOT / "eng/policy/dependency-policy.json"
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    active = policy["reviewReceipt"]
    previous = policy["review"]["previousReceipt"] if active == RECEIPT else active
    if previous is None or previous == RECEIPT:
        raise SystemExit(f"Unexpected dependency review predecessor: {active}")

    # Idempotent: a refresh after a rebase finds the rows already removed; the locked-closure check below is the guard.
    for key in REMOVED_COORDINATES:
        policy["nugetClosure"].pop(key, None)

    locked = dependency_policy.closure(ROOT)
    if any("osx" in key for key in locked):
        raise SystemExit("The locked graph still contains an osx coordinate.")
    if set(locked) != set(policy["nugetClosure"]):
        raise SystemExit("The locked graph does not match the admitted closure after removing the osx rows.")

    input_hashes = dependency_policy.hashes(ROOT)
    global_json = json.loads((ROOT / "global.json").read_text(encoding="utf-8"))
    policy["inputHashes"] = input_hashes
    policy["reviewReceipt"] = RECEIPT
    policy["review"].update(
        {
            "owner": "w-deku-20261008-gov-30",
            "reviewer": "Pending independent exact-head dependency-admission review before merge.",
            "reviewedOn": "2026-10-08",
            "baselineCommit": BASELINE_COMMIT,
            "maintenanceAssessment": (
                "GOV.30 adds no dependency. It removes the two macOS-RID ILCompiler 10.0.11 runtime-pack admissions "
                "(MIT) and the macOS-RID net10.0 lock sections of the ContentSandbox, "
                "ContentSandbox Fixture, LocalRpcAotTests, ReleaseArtifactTests GrpcWeb and Realtime locks, because "
                "eng/build/desktop-rids.props no longer lists the two macOS RIDs (P2-023). The remaining desktop RID "
                "set is win-x64, win-arm64 and linux-x64; linux-arm64 is not added. Every other coordinate, version, "
                "content hash and source record is unchanged, and the locks equal their predecessors with only the macOS "
                "sections removed. This successor chains from the receipt active on the base branch and preserves all "
                "earlier receipts."
            ),
            "upgradeChecks": {
                "compilation": "With the pinned SDK 10.0.400 in the local WSL2 Debian distribution (Debian 13, kernel 6.18.40.1-microsoft-standard-WSL2) on a Linux-native copy: the five affected locks were regenerated by restore (--use-lock-file) and every affected project passes --locked-mode restore; a Release build of the five affected projects completes with 0 warnings and 0 errors; the ArcForges.ContentSandbox.Tests project restores locked and its test run passes. The regenerated locks differ from their predecessors only by the removed macOS-RID sections.",
                "aot-trim": "No trim, AOT or analyzer setting changes; the win-x64 and linux-x64 Native AOT publish paths are unchanged. Affected Native AOT probes are not re-published by this successor.",
                "compatibility": "No public API, wire schema or contract changes; the LocalRpcAotTests publish help text and README drop only the macOS RID lines.",
                "licence-provenance": "Removes two MIT coordinates with their recorded nuspec evidence; no coordinate is added and no source or licence record changes.",
                "security-sbom": "The remaining locked graph is unchanged and keeps its NuGet audit; removing an unused RID admission reduces the admitted closure. No claim of absent current advisories is made.",
                "runtime-performance-migration": "No runtime, performance or migration change; no macOS runtime or CI obligation is created or claimed.",
                "framework-runtime-posture": "No framework major, native ABI, Android or SDK change; global.json remains on .NET SDK 10.0.400.",
            },
            "inputHashes": input_hashes,
            "frameworkVersions": {"dotnetSdk": global_json["sdk"]["version"]},
            "previousReceipt": previous,
        }
    )

    receipt = {key: policy[key] for key in ("review", "nugetClosure", "pythonClosure")}
    (ROOT / RECEIPT).write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8", newline="\n")
    policy_path.write_text(json.dumps(policy, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {RECEIPT}; predecessor {previous}; {len(locked)} locked coordinates; {len(input_hashes)} dependency inputs.")


if __name__ == "__main__":
    main()
