<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ArcChat.Mobile.CloudClient</AssemblyName>
    <RootNamespace>ArcChat.Mobile.CloudClient</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArcChat.Mobile.Application\ArcChat.Mobile.Application.csproj" />
    <ProjectReference Include="..\ArcChat.Mobile.Contracts\ArcChat.Mobile.Contracts.csproj" />
  </ItemGroup>
</Project>
