<Project>
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <Import Project="../../../Directory.Packages.props" />
  <ItemGroup>
    <PackageVersion Include="ArcForges.Foundation" Version="1.0.0-ci.29.1" />
    <PackageVersion Include="ArcForges.Application.Abstractions" Version="1.0.0-ci.29.1" />
  </ItemGroup>
</Project>
