<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ArcForges.Web.Application</AssemblyName>
    <RootNamespace>ArcForges.Web.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\ArcForges.Contracts.PublicApi\ArcForges.Contracts.PublicApi.csproj" />
    <ProjectReference Include="..\..\Contracts\ArcForges.Contracts.Realtime\ArcForges.Contracts.Realtime.csproj" />
  </ItemGroup>
</Project>
